export const INDONESIA_CITIES = [
    "JAKARTA BARAT",
    "JAKARTA PUSAT",
    "JAKARTA SELATAN",
    "JAKARTA TIMUR",
    "JAKARTA UTARA",
    "BOGOR",
    "DEPOK",
    "TANGERANG",
    "TANGERANG SELATAN",
    "BEKASI",
    "BANDUNG",
    "BANDUNG BARAT",
    "CIMAHI",
    "CIREBON",
    "SEMARANG",
    "SALATIGA",
    "SURAKARTA",
    "YOGYAKARTA",
    "SLEMAN",
    "BANTUL",
    "SURABAYA",
    "SIDOARJO",
    "MALANG",
    "GRESIK",
    "PASURUAN",
    "MOJOKERTO",
    "DENPASAR",
    "BADUNG",
    "GIANYAR",
    "MEDAN",
    "BINJAI",
    "PEKANBARU",
    "BATAM",
    "PALEMBANG",
    "LAMPUNG",
    "PONTIANAK",
    "BALIKPAPAN",
    "SAMARINDA",
    "BANJARMASIN",
    "MANADO",
    "MAKASSAR",
    "PALOPO",
    "KENDARI",
    "PALU",
    "MAMUJU",
    "JAYAPURA",
    "SORONG",
    "AMBON",
    "MATARAM",
    "KUPANG",
];
